server:
  port: 8765

spring:
  application:
    name: feign
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ConnectTimeout: 3500
  ReadTimeout: 3500
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 0

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    ClientFeign#getUser(String):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    default:
      execution:
        timeout:
          enabled: true #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
        isolation:
          thread:
            timeoutInMilliseconds: 5000

